### ISSUE TITLE
Middlewares examples not working

### ISSUE THREAD

**Issue by samuelcsouza** [cirospaciari/socketify.py#105]
I'm trying to reproduce the examples of middlewares in this [link](https://docs.socketify.dev/middlewares.html) of the documentation but it's not working.

```python
# you can use an Middleware router to add middlewares to every route you set
auth_router = MiddlewareRouter(app, auth)
auth_router.get("/", home)
# you can also mix middleware() with MiddlewareRouter
auth_router.get("/another", middleware(another_middie, home))

# you can also pass multiple middlewares on the MiddlewareRouter
other_router = MiddlewareRouter(app, auth, another_middie)
other_router.get("/another_way", home)
```

I got this error:

```bash
Traceback (most recent call last):
  File "/home/samuel/my-project/middlewares.py", line 40, in <module>
    router.get("/", home)
  File "/home/samuel/my-project/venv/lib/pypy3.9/site-packages/socketify/helpers.py", line 366, in get
    middies = list(*self.middlewares)
TypeError: 'function' object is not iterable
```

I can resolve by replacing the _middlewares functions_ with square brackets:

```python
# you can use an Middleware router to add middlewares to every route you set
auth_router = MiddlewareRouter(app, [auth])
auth_router.get("/", home)
# you can also mix middleware() with MiddlewareRouter
auth_router.get("/another", middleware(another_middie, home))

# you can also pass multiple middlewares on the MiddlewareRouter
other_router = MiddlewareRouter(app, [auth, another_middie])
other_router.get("/another_way", home)
```

But if you using the `list(middleware_functions)` conversion, which is currently the source code implementation, the error still persists

```bash
Traceback (most recent call last):
  File "/home/samuel/my-project/middlewares.py", line 39, in <module>
    router = MiddlewareRouter(app, list(auth))
TypeError: 'function' object is not iterable
```

**Comment by cirospaciari** [comment]
Thanks for reporting, is outdated I will update the examples and docs it in the next release thanks!
