### ISSUE TITLE
undefined symbol: uv_handle_get_data

### ISSUE THREAD

**Issue by RYefccd** [cirospaciari/socketify.py#147]
**Describe the bug**
socketify.py link libuv get undefine symbol.

**To Reproduce**
1. lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

2.python -V
Python 3.11.5

3. pip list
cffi       1.16.0
pip        23.3.1
pycparser  2.21
setuptools 68.0.0
socketify  0.0.27
wheel      0.41.2

4.main2.py
```python
from socketify import App

app = App()
app.get("/", lambda res, req: res.end("Hello World socketify from Python!"))
app.listen(3000, lambda config: print("Listening on port http://localhost:%d now\n" % config.port))
app.run()
```

5.python -m socketify main2:app 
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/ryefccd/anaconda3/envs/whtrq/lib/python3.11/site-packages/socketify/__init__.py", line 5, in <module>
    from .socketify import (
  File "/home/ryefccd/anaconda3/envs/whtrq/lib/python3.11/site-packages/socketify/socketify.py", line 12, in <module>
    from .native import ffi, lib
  File "/home/ryefccd/anaconda3/envs/whtrq/lib/python3.11/site-packages/socketify/native.py", line 409, in <module>
    lib = ffi.dlopen(library_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryefccd/anaconda3/envs/whtrq/lib/python3.11/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryefccd/anaconda3/envs/whtrq/lib/python3.11/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryefccd/anaconda3/envs/whtrq/lib/python3.11/site-packages/cffi/api.py", line 828, in _load_backend_lib
    return backend.load_library(path, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: cannot load library '/home/ryefccd/anaconda3/envs/whtrq/lib/python3.11/site-packages/socketify/libsocketify_linux_amd64.so': /home/ryefccd/anaconda3/envs/whtrq/lib/python3.11/site-packages/socketify/libsocketify_linux_amd64.so: undefined symbol: uv_handle_get_data

how to link with libuv

**Comment by cirospaciari** [comment]
looks like is missing libuv package you can install on debian-like distros libuv and zlib using:
```bash
apt install libuv1 zlib1g
```
