### ISSUE TITLE
Segmentation Fault in uWS::WebSocket::send Function

### ISSUE THREAD

**Issue by ArthoPacini** [cirospaciari/socketify.py#197]
**Describe the bug**
The program crashes. The fault seems to occur randomly and is not tied to the number of workers (`-w` parameter).

## Environment
Python 3.10.14 (75b3de9d9035, Apr 21 2024, 10:54:48)
[PyPy 7.3.16 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
Running on Docker Container in Debian GNU/Linux 11 (bullseye)
Kernel: 6.10.0-linuxkit

**To Reproduce**
I didn't pinpoint this (yet), but I am trying to. Gonna get more info when possible.

**Additional context**
I've tried running valgrind on it (pypy3 -m socketify main:app -w 4), using:

Then this is the 'bt' on the seg fault:

```cpp
Core was generated by 'pypy3 -m socketify main:app -w 4'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f6bc50bf8fd in uWS::WebSocket<false, true, void*>::send(std::basic_string_view<char, std::char_traits<char> >, uWS::OpCode, bool, bool) () from /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so
[Current thread is 1 (Thread 0x7f6bc780d780 (LWP 79120))]
(gdb) bt
#0  0x00007f6bc50bf8fd in uWS::WebSocket<false, true, void*>::send(std::basic_string_view<char, std::char_traits<char> >, uWS::OpCode, bool, bool) () from /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so
#1  0x00007f6bc7605e2c in ffi_call_unix64 () from /opt/pypy/bin/../lib/libffi.so.6
#2  0x00007f6bc7605755 in ffi_call () from /opt/pypy/bin/../lib/libffi.so.6
#3  0x00007f6bc8b2605b in pypy_g_ccall_ffi_call__ffi_cifPtr_arrayPtr_arrayPtr_arr () from /opt/pypy/bin/libpypy3.10-c.so
#4  0x00007f6bc9bb9831 in pypy_g_jit_ffi_call () from /opt/pypy/bin/libpypy3.10-c.so
#5  0x00007f6bc8fe5918 in pypy_g_W_CTypeFunc__call () from /opt/pypy/bin/libpypy3.10-c.so
#6  0x00007f6bc8aba889 in pypy_g_BuiltinActivation_UwS_W_CData_args_w__run () from /opt/pypy/bin/libpypy3.10-c.so
#7  0x00007f6bc8d0f38b in pypy_g_BuiltinCode_funcrun_obj () from /opt/pypy/bin/libpypy3.10-c.so
#8  0x00007f6bc8db6815 in pypy_g_call_valuestack__AccessDirect_None () from /opt/pypy/bin/libpypy3.10-c.so
#9  0x00007f6bc971460d in pypy_g_CALL_METHOD__AccessDirect_star_1 () from /opt/pypy/bin/libpypy3.10-c.so
#10 0x00007f6bc8dbae3d in pypy_g_dispatch_bytecode__AccessDirect_None () from /opt/pypy/bin/libpypy3.10-c.so
#11 0x00007f6bc8d83832 in pypy_g_handle_bytecode__AccessDirect_None () from /opt/pypy/bin/libpypy3.10-c.so
#12 0x00007f6bc94e1b60 in pypy_g_portal_11 () from /opt/pypy/bin/libpypy3.10-c.so
#13 0x00007f6bc98c6a9b in pypy_g_ll_portal_runner__Unsigned_Bool_pypy_interpreter () from /opt/pypy/bin/libpypy3.10-c.so
#14 0x00007f6bc8d456da in pypy_g_execute_frame () from /opt/pypy/bin/libpypy3.10-c.so
#15 0x00007f6bc9cb1456 in __vmprof_eval_vmprof () from /opt/pypy/bin/libpypy3.10-c.so
#16 0x00007f6bc971460d in pypy_g_CALL_METHOD__AccessDirect_star_1 () from /opt/pypy/bin/libpypy3.10-c.so
#17 0x00007f6bc8dbae3d in pypy_g_dispatch_bytecode__AccessDirect_None () from /opt/pypy/bin/libpypy3.10-c.so
#18 0x00007f6bc8d83832 in pypy_g_handle_bytecode__AccessDirect_None () from /opt/pypy/bin/libpypy3.10-c.so
#19 0x00007f6bc94e1b60 in pypy_g_portal_11 () from /opt/pypy/bin/libpypy3.10-c.so
#20 0x00007f6bc98c6a9b in pypy_g_ll_portal_runner__Unsigned_Bool_pypy_interpreter () from /opt/pypy/bin/libpypy3.10-c.so
#21 0x00007f6bc8d456da in pypy_g_execute_frame () from /opt/pypy/bin/libpypy3.10-c.so
#22 0x00007f6bc9cb1456 in __vmprof_eval_vmprof () from /opt/pypy/bin/libpypy3.10-c.so
#23 0x00007f6bc971460d in pypy_g_CALL_METHOD__AccessDirect_star_1 () from /opt/pypy/bin/libpypy3.10-c.so
#24 0x00007f6bc8dbae3d in pypy_g_dispatch_bytecode__AccessDirect_None () from /opt/pypy/bin/libpypy3.10-c.so
#25 0x00007f6bc8d83832 in pypy_g_handle_bytecode__AccessDirect_None () from /opt/pypy/bin/libpypy3.10-c.so
#26 0x00007f6bc94e1b60 in pypy_g_portal_11 () from /opt/pypy/bin/libpypy3.10-c.so
#27 0x00007f6bc98c6a9b in pypy_g_ll_portal_runner__Unsigned_Bool_pypy_interpreter () from /opt/pypy/bin/libpypy3.10-c.so
#28 0x00007f6bc8d456da in pypy_g_execute_frame () from /opt/pypy/bin/libpypy3.10-c.so
#29 0x00007f6bc9cb1456 in __vmprof_eval_vmprof () from /opt/pypy/bin/libpypy3.10-c.so
#30 0x00007f6bc8d97b55 in pypy_g_ObjSpace_call () from /opt/pypy/bin/libpypy3.10-c.so
#31 0x00007f6bc9003853 in pypy_g_W_ExternPython_do_invoke () from /opt/pypy/bin/libpypy3.10-c.so
#32 0x00007f6bc98d2ed3 in pypy_g_ll_portal_runner__pypy_interpreter_eval_CodePtr_ () from /opt/pypy/bin/libpypy3.10-c.so
#33 0x00007f6bc8fb18cc in pypy_g_W_ExternPython_invoke () from /opt/pypy/bin/libpypy3.10-c.so
#34 0x00007f6bc90064cb in pypy_g_invoke_callback () from /opt/pypy/bin/libpypy3.10-c.so
#35 0x00007f6bc8cdf51e in pypy_g_wrapper_24 () from /opt/pypy/bin/libpypy3.10-c.so
#36 0x00007f6bc7605c1b in ffi_closure_unix64_inner () from /opt/pypy/bin/../lib/libffi.so.6
#37 0x00007f6bc7605f94 in ffi_closure_unix64 () from /opt/pypy/bin/../lib/libffi.so.6
#38 0x00007f6bc50ab8d2 in uws_ws_cork () from /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so
#39 0x00007f6bc3b2469b in ?? ()
#40 0x0000000000000000 in ?? ()
(gdb) 
```

Maybe trying to send a message though a socket that is already closed or non existent / invalid pointer? 

How can I use a debug version of the uWS lib or any other resources so I can have debug symbols and better understand the state of the application on this crash?

On my application, upon receiving a message, by the time the message will be sent the connection could already be closed. I will try a stress test on this, but maybe it is not checking some kind of structure about the actual socket to be written to?

**Comment by ArthoPacini** [comment]
I've tried running the same script on this issue: https://github.com/uNetworking/uWebSockets/issues/1692, It didn't triggered any segmentation fault, the opening and closing of tons of connections doesn't seem to be the problem, but none of those connections sent any messages besides regular protocol standard stuff.

Will later try out opening connections, sending some data, adding some delay on the server to reply the data, and then closing the connection, to check if the system can deal with closed or non existent connections.

**Comment by ArthoPacini** [comment]
I've just modified the script to also send a message after connecting, closing and not waiting for any message back. It seems to trigger the segfault:

```cpp
==47160== Invalid read of size 8
==47160==    at 0xC210D04: us_socket_context (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0xC1E0847: uws_ws_cork (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0x179445EE: ???
==47160==    by 0x183AEE43: ???
==47160==    by 0x6B2F9D2: pypy_g_ll_dict_setitem__DICTPtr_Address_Address (in /opt/pypy/bin/libpypy3.10-c.so)
==47160==    by 0x81D1326: __libc_recv (recv.c:28)
==47160==    by 0x81D1326: recv (recv.c:23)
==47160==    by 0x916056F: ???
==47160==  Address 0xb6fc878 is 24 bytes inside a block of size 200 free'd
==47160==    at 0x48399AB: free (vg_replace_malloc.c:538)
==47160==    by 0xC20DA14: ??? (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0xC5167E8: uv_run (in /usr/lib/x86_64-linux-gnu/libuv.so.1.0.0)
==47160==    by 0x1795CCE6: ???
==47160==    by 0x9111017: ???
==47160==    by 0x819F53F: ???
==47160==    by 0x91137E7: ???
==47160==    by 0x91137BF: ???
==47160==    by 0xA953A5F: ???
==47160==    by 0x42: ???
==47160==    by 0x89BE01F: ???
==47160==    by 0x9113707: ???
==47160==  Block was alloc'd at
==47160==    at 0x483AD7B: realloc (vg_replace_malloc.c:834)
==47160==    by 0xC20DE62: us_poll_resize (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0xC20D833: us_socket_context_adopt_socket (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0xC1F7B75: void uWS::HttpResponse<false>::upgrade<void*>(void*&&, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, us_socket_context_t*) (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0xC1E224D: uws_res_upgrade (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0x83C7E2B: ffi_call_unix64 (in /opt/pypy/lib/libffi.so.6)
==47160==    by 0x83C7754: ffi_call (in /opt/pypy/lib/libffi.so.6)
==47160==    by 0x596D05A: pypy_g_ccall_ffi_call__ffi_cifPtr_arrayPtr_arrayPtr_arr (in /opt/pypy/bin/libpypy3.10-c.so)
==47160==    by 0x5E2C917: pypy_g_W_CTypeFunc__call (in /opt/pypy/bin/libpypy3.10-c.so)
==47160==    by 0x5901888: pypy_g_BuiltinActivation_UwS_W_CData_args_w__run (in /opt/pypy/bin/libpypy3.10-c.so)
==47160==    by 0x5B5638A: pypy_g_BuiltinCode_funcrun_obj (in /opt/pypy/bin/libpypy3.10-c.so)
==47160==    by 0x5BFD814: pypy_g_call_valuestack__AccessDirect_None (in /opt/pypy/bin/libpypy3.10-c.so)
==47160== 
==47160== Invalid read of size 8
==47160==    at 0xC210D04: us_socket_context (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0xC1E086C: uws_ws_cork (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0x179445EE: ???
==47160==    by 0x183AEE43: ???
==47160==    by 0x6B2F9D2: pypy_g_ll_dict_setitem__DICTPtr_Address_Address (in /opt/pypy/bin/libpypy3.10-c.so)
==47160==    by 0x81D1326: __libc_recv (recv.c:28)
==47160==    by 0x81D1326: recv (recv.c:23)
==47160==    by 0x916056F: ???
==47160==  Address 0xb6fc878 is 24 bytes inside a block of size 200 free'd
==47160==    at 0x48399AB: free (vg_replace_malloc.c:538)
==47160==    by 0xC20DA14: ??? (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0xC5167E8: uv_run (in /usr/lib/x86_64-linux-gnu/libuv.so.1.0.0)
==47160==    by 0x1795CCE6: ???
==47160==    by 0x9111017: ???
==47160==    by 0x819F53F: ???
==47160==    by 0x91137E7: ???
==47160==    by 0x91137BF: ???
==47160==    by 0xA953A5F: ???
==47160==    by 0x42: ???
==47160==    by 0x89BE01F: ???
==47160==    by 0x9113707: ???
==47160==  Block was alloc'd at
==47160==    at 0x483AD7B: realloc (vg_replace_malloc.c:834)
==47160==    by 0xC20DE62: us_poll_resize (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0xC20D833: us_socket_context_adopt_socket (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0xC1F7B75: void uWS::HttpResponse<false>::upgrade<void*>(void*&&, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, us_socket_context_t*) (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0xC1E224D: uws_res_upgrade (in /opt/pypy/lib/pypy3.10/site-packages/socketify/libsocketify_linux_amd64.so)
==47160==    by 0x83C7E2B: ffi_call_unix64 (in /opt/pypy/lib/libffi.so.6)
==47160==    by 0x83C7754: ffi_call (in /opt/pypy/lib/libffi.so.6)
==47160==    by 0x596D05A: pypy_g_ccall_ffi_call__ffi_cifPtr_arrayPtr_arrayPtr_arr (in /opt/pypy/bin/libpypy3.10-c.so)
==47160==    by 0x5E2C917: pypy_g_W_CTypeFunc__call (in /opt/pypy/bin/libpypy3.10-c.so)
==47160==    by 0x5901888: pypy_g_BuiltinActivation_UwS_W_CData_args_w__run (in /opt/pypy/bin/libpypy3.10-c.so)
==47160==    by 0x5B5638A: pypy_g_BuiltinCode_funcrun_obj (in /opt/pypy/bin/libpypy3.10-c.so)
==47160==    by 0x5BFD814: pypy_g_call_valuestack__AccessDirect_None (in /opt/pypy/bin/libpypy3.10-c.so)
==47160== 
```

I am using on ws_message I call ws.cork_send(), may this is the problem?

**Comment by ArthoPacini** [comment]
It seems that even with ws.send() it still persists....

**Comment by ArthoPacini** [comment]
on the docs it states:

```# clone the current instance to preserve it (you need to watch for closed connections when using it)```

on the API Reference of the WebSocket, how would I clone it? just set it to a local variable?

**Comment by ArthoPacini** [comment]
```python
async def ws_message(ws, message, opcode):
    ws_copy = ws

    ws_copy.cork_send(message=response, opcode=opcode)
```

segfaults


```python
async def ws_message(ws, message, opcode):
    ws_copy = ws

    if ws_copy:
        ws_copy.cork_send(message=response, opcode=opcode)
```

also segfaults.

tomorrow will try to create a mini reproducible code on this crash trigger.

**Comment by ArthoPacini** [comment]
Alright, I got a reproducible code:


# Socketify server
```python
from socketify import App, CompressOptions, AppListenOptions
import logging
import asyncio
import faulthandler
faulthandler.enable()

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(message)s')


def ws_open(ws):
    user = ws.get_user_data()
    logging.debug(f"Websocket Connection Opened. Connection: {ws}, User Data: {user}")

async def ws_message(ws, message, opcode):
    await asyncio.sleep(1.0) # comment this out and the error goes away
    ws.cork_send(message=message, opcode=opcode)

async def ws_upgrade(res, req, socket_context):

    key = req.get_header("sec-websocket-key")
    protocol = req.get_header("sec-websocket-protocol")
    extensions = req.get_header("sec-websocket-extensions")
    
    res.upgrade(key, protocol, extensions, socket_context, None)



def make_app(app):    
    app.ws("/api/v1/ws/*", {
        'compression': CompressOptions.SHARED_COMPRESSOR,
        'max_payload_length': 256 * 1024 * 1024, #16 Megabytes
        "max_backpressure": 1024,
        'idle_timeout': 960,
        'open': ws_open,
        'message': ws_message,
        #'close': ws_close,
        #'error': ws_error,
        "upgrade": ws_upgrade,
        'drain': lambda ws: print('WebSocket backpressure: %i' % ws.get_buffered_amount())
    })

app = App()
make_app(app)

app.listen(AppListenOptions(port=5555, host="0.0.0.0"), lambda config: print(f"Listening on port http://{config.host}:%d now\n" % (config.port)))
app.run()
```

Note that it got the `await asyncio.sleep(1.0)` uncommented, this will add a short delay to send the message, if this is commented out, it does segfaults. It is just used to simulate a processing. Some internal processing of the income message could wait more than enough to the connection to be closed.

To test it and throw a segmentation fault, you can just run this code inside any chromium browser F12 console (change the port and endpoint), this will stress test, opening a bunch of connection, sending some messages, and closing afterwards:

```javascript
// Data object to send
let message = {
    "hello": "world"
};

let created = 0;
let closed = 0;
const CONCURRENCY = 50;

// Function to open WebSocket connections
function openWebSocket() {
    if (created - closed >= CONCURRENCY) {
        return;
    }

    created += 1;
    const ws = new WebSocket('ws://localhost:5555/api/v1/ws/');

    ws.onerror = (error) => {
        console.error('ERROR', created, closed, error);
    };

    ws.onopen = () => {
        ws.send(JSON.stringify(message)); // Send a message immediately after opening the connection
        ws.close();       // Close the WebSocket right after sending the message
    };

    ws.onclose = () => {
        closed += 1;
    };
}

// Function to start the WebSocket stress test
function startStressTest() {
    const intervalId = setInterval(() => {
        openWebSocket();
    }, 1);

    // Optional: clear interval based on some condition or provide a way to stop it
    // Uncomment to stop after 10 seconds
    // setTimeout(() => clearInterval(intervalId), 10000);
}

// Keep printing statistics about created and closed connections
setInterval(() => {
    console.log(`${created}/${closed} ${created-closed}`);
}, 1000);

// Start stress test immediately (no need to wait for component mount)
startStressTest();

```


faulthandler:

```cpp
Fatal Python error: Segmentation fault

Stack (most recent call first, approximate line numbers):
  File "/opt/pypy/lib/pypy3.10/site-packages/socketify/socketify.py", line 1459 in cork
  File "/opt/pypy/lib/pypy3.10/site-packages/socketify/socketify.py", line 1405 in cork_send
  File "/workspaces/stress-test/segfault_test.py", line 15 in ws_message
  File "/opt/pypy/lib/pypy3.10/site-packages/socketify/loop.py", line 11 in task_wrapper
  File "/opt/pypy/lib/pypy3.10/site-packages/socketify/tasks.py", line 602 in factory_task_wrapper
  File "/opt/pypy/lib/pypy3.10/site-packages/socketify/tasks.py", line 491 in __step
  File "/opt/pypy/lib/pypy3.10/site-packages/socketify/tasks.py", line 583 in __wakeup
  File "/opt/pypy/lib/pypy3.10/_contextvars.py", line 38 in run
  File "/opt/pypy/lib/pypy3.10/asyncio/events.py", line 78 in _run
  File "/opt/pypy/lib/pypy3.10/asyncio/base_events.py", line 1832 in _run_once
  File "/opt/pypy/lib/pypy3.10/asyncio/base_events.py", line 589 in run_forever
  File "/opt/pypy/lib/pypy3.10/site-packages/socketify/loop.py", line 118 in run
  File "/opt/pypy/lib/pypy3.10/site-packages/socketify/socketify.py", line 3367 in run
  File "/workspaces/stress-test/segfault_test.py", line 1 in <module>
  File "<builtin>/app_main.py", line 1035 in execfile
  File "<builtin>/app_main.py", line 133 in run_toplevel
  File "<builtin>/app_main.py", line 748 in run_command_line
  File "<builtin>/app_main.py", line 1149 in entry_point
Segmentation fault
```

How can I check if the connection is actually valid before sending the message? Shouldn't this be built into the lib? What am I doing wrong here?


The problem persists if I use:

```python
async def ws_message(ws, message, opcode):
    await asyncio.sleep(1.0) # comment this out and the error goes away
    
    if (ws):
        ws.cork_send(message=message, opcode=opcode)
```

or even:

```python
async def ws_message(ws, message, opcode):
    ws_copy = ws
    await asyncio.sleep(1.0) # comment this out and the error goes away
    
    if (ws_copy):
        ws_copy.cork_send(message=message, opcode=opcode)
```

I am using Brave Browser to run the stress javascript code.

Also the socketify version = 0.0.27 (cause 0.0.28 has high cpu usage)

**Comment by ArthoPacini** [comment]
This also segfaults:

```python
async def ws_message(ws, message, opcode):
    await asyncio.sleep(1.0) # comment this out and the error goes away
    
    try:
        ws.cork_send(message=message, opcode=opcode)
    except:
        pass
```

**Comment by ArthoPacini** [comment]
Using clone, also segfaults:

```python
async def ws_message(ws, message, opcode):
    ws_copy = ws.clone()
    await asyncio.sleep(1.0) # comment this out and the error goes away
    
    try:
        ws_copy.send(message=message, opcode=opcode)
    except:
        pass
```
or
```python
async def ws_message(ws, message, opcode):
    ws_copy = ws.clone()
    await asyncio.sleep(1.0) # comment this out and the error goes away
    
    try:
        if (ws_copy):
            ws_copy.send(message=message, opcode=opcode)
    except:
        pass
```

**Comment by ArthoPacini** [comment]
It seems that it's accessing an already invalid `ws` object. It only happens when using async functions..

```python
from socketify import App, CompressOptions, AppListenOptions
import logging
import asyncio
import faulthandler
import time
faulthandler.enable()

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(message)s')


async def ws_open(ws):
    user = ws.get_user_data()
    logging.debug(f"Websocket Connection Opened. Connection: {ws}, User Data: {user}")

async def ws_message(ws, message, opcode):
    await asyncio.sleep(1.0) # comment this out and the error goes away
    user = ws.get_user_data()

async def ws_upgrade(res, req, socket_context):

    key = req.get_header("sec-websocket-key")
    protocol = req.get_header("sec-websocket-protocol")
    extensions = req.get_header("sec-websocket-extensions")
    
    res.upgrade(key, protocol, extensions, socket_context, {"is_connected":True})

async def ws_close(ws, code, message):
    user = ws.get_user_data()
    user["is_connected"] = False
    logging.debug(f"Websocket Connection Closed. Connection: {ws}, User Data: {user}")


def make_app(app):    
    app.ws("/api/v1/ws/*", {
        'compression': CompressOptions.SHARED_COMPRESSOR,
        'max_payload_length': 256 * 1024 * 1024, #16 Megabytes
        "max_backpressure": 1024,
        'idle_timeout': 960,
        'open': ws_open,
        'message': ws_message,
        'close': ws_close,
        #'error': ws_error,
        "upgrade": ws_upgrade,
        'drain': lambda ws: print('WebSocket backpressure: %i' % ws.get_buffered_amount())
    })

app = App()
make_app(app)

app.listen(AppListenOptions(port=5555, host="0.0.0.0"), lambda config: print(f"Listening on port http://{config.host}:%d now\n" % (config.port)))
app.run()
```

This also throws the segfault, because it is trying to access the user data of the ws object after 1 second, when it is already closed. it then segfaults. how can we check if the ws is valid before accessing it?

**Comment by ArthoPacini** [comment]
Alright, I think I found an temporary solution...

I've build a temporary registry that uses the ws object as the key to a hashmap that store boolean values, True is set when the connection is open, False is set when the connection is closed. For any interaction with the `ws` object it should check its status in the registry.

By changing the line `if registry.check_is_open(ws):` to `if True:` in the `ws_message` function it will segfault...

There is still a tiny window from the check and the actual interaction with the ws object that could lead to a segfault. Is there a better solution @cirospaciari ? 

```python
from socketify import App, CompressOptions, AppListenOptions
import logging
import asyncio
import faulthandler
import time
faulthandler.enable()

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(message)s')



class WebSocketRegistry:
    def __init__(self):
        self.connections = {}

    def new_connection(self, ws):
        """ Register a new connection as open """
        self.connections[ws] = True
        logging.debug(f"Registered new WebSocket: {ws}")

    def close_connection(self, ws):
        """ Set the connection status to closed """
        if ws in self.connections:
            self.connections[ws] = False
            logging.debug(f"WebSocket closed: {ws}")

    def check_is_open(self, ws):
        """ Check if the connection is still open """
        if ws in self.connections and self.connections[ws]:
            return True
        # Clean up closed connection from the registry
        logging.debug(f"WebSocket is already closed, removing it: {ws}")
        self.remove_connection(ws)
        return False

    def remove_connection(self, ws):
        """ Remove the connection from the registry """
        if ws in self.connections:
            del self.connections[ws]
            logging.debug(f"WebSocket removed: {ws}")

# Update your WebSocket handlers to use WebSocketRegistry
registry = WebSocketRegistry()

async def ws_open(ws):
    registry.new_connection(ws)
    user = ws.get_user_data()
    logging.debug(f"Websocket Connection Opened. Connection: {ws}, User Data: {user}")

async def ws_message(ws, message, opcode):
    await asyncio.sleep(1.0) # comment this out and the error goes away
    
     # Change this to `if True:` and you gonna get SegFault
    if registry.check_is_open(ws):
        user = ws.get_user_data()
        logging.debug(f"Websocket Connection Sending Data. Connection: {ws}, User Data: {user}")   
        ws.send(message=message, opcode=opcode)
    else:
        pass

async def ws_upgrade(res, req, socket_context):

    key = req.get_header("sec-websocket-key")
    protocol = req.get_header("sec-websocket-protocol")
    extensions = req.get_header("sec-websocket-extensions")
    
    res.upgrade(key, protocol, extensions, socket_context, None)

async def ws_close(ws, code, message):
    user = ws.get_user_data()
    logging.debug(f"Websocket Connection Closed. Connection: {ws}, User Data: {user}")
    registry.close_connection(ws)


def make_app(app):    
    app.ws("/api/v1/ws/*", {
        'compression': CompressOptions.SHARED_COMPRESSOR,
        'max_payload_length': 256 * 1024 * 1024, #16 Megabytes
        "max_backpressure": 1024,
        'idle_timeout': 960,
        'open': ws_open,
        'message': ws_message,
        'close': ws_close,
        #'error': ws_error,
        "upgrade": ws_upgrade,
        'drain': lambda ws: print('WebSocket backpressure: %i' % ws.get_buffered_amount())
    })

app = App()
make_app(app)

app.listen(AppListenOptions(port=5555, host="0.0.0.0"), lambda config: print(f"Listening on port http://{config.host}:%d now\n" % (config.port)))
app.run()
```

**Comment by cirospaciari** [comment]
Memory managamento on socketify is bad at this moment Im rewritting the native code because of this, also the async with websockets at this moment is not great, thats why so many segfaults.

**Comment by cirospaciari** [comment]
Duplicated of https://github.com/cirospaciari/socketify.py/issues/141

**Comment by ArthoPacini** [comment]
yeah, my latest message reply system actually doesn't work because the `ws` object pointer always changes.

this might be it for a temporary solution, assigning an random connection id:

```python
from socketify import App, CompressOptions, AppListenOptions
import logging
import asyncio
import faulthandler
import time
faulthandler.enable()
import random

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(message)s')



class WebSocketRegistry:
    def __init__(self):
        self.connections = {}

    def new_connection(self, ws):
        """ Register a new connection as open """
        self.connections[ws] = True
        logging.debug(f"Registered new WebSocket: {ws}")

    def close_connection(self, ws):
        """ Set the connection status to closed """
        if ws in self.connections:
            self.connections[ws] = False
            logging.debug(f"WebSocket closed: {ws}")

    def check_is_open(self, ws):
        """ Check if the connection is still open """
        if ws in self.connections and self.connections[ws]:
            return True
        # Clean up closed connection from the registry
        logging.debug(f"WebSocket is already closed, removing it: {ws}")
        self.remove_connection(ws)
        return False

    def remove_connection(self, ws):
        """ Remove the connection from the registry """
        if ws in self.connections:
            del self.connections[ws]
            logging.debug(f"WebSocket removed: {ws}")

# Update your WebSocket handlers to use WebSocketRegistry
registry = WebSocketRegistry()

async def ws_open(ws):
    user = ws.get_user_data()
    registry.new_connection(user["connection_id"])
    logging.debug(f"Websocket Connection Opened. Connection: {ws}, User Data: {user}")

async def ws_message(ws, message, opcode):
    user = ws.get_user_data()
    connection_id = user["connection_id"]
    await asyncio.sleep(1.0) # comment this out and the error goes away
    
     # Change this to `if True:` and you gonna get SegFault
    if registry.check_is_open(connection_id):
        user = ws.get_user_data()
        logging.debug(f"Websocket Connection Sending Data. Connection: {ws}, User Data: {user}")   
        ws.send(message=message, opcode=opcode)
    else:
        pass

async def ws_upgrade(res, req, socket_context):

    key = req.get_header("sec-websocket-key")
    protocol = req.get_header("sec-websocket-protocol")
    extensions = req.get_header("sec-websocket-extensions")
    
    
    res.upgrade(key, protocol, extensions, socket_context, {"connection_id":random.randint(1,999999)})

async def ws_close(ws, code, message):
    user = ws.get_user_data()
    logging.debug(f"Websocket Connection Closed. Connection: {ws}, User Data: {user}")
    registry.close_connection(user["connection_id"])


def make_app(app):    
    app.ws("/api/v1/ws/*", {
        'compression': CompressOptions.SHARED_COMPRESSOR,
        'max_payload_length': 256 * 1024 * 1024, #16 Megabytes
        "max_backpressure": 1024,
        'idle_timeout': 960,
        'open': ws_open,
        'message': ws_message,
        'close': ws_close,
        #'error': ws_error,
        "upgrade": ws_upgrade,
        'drain': lambda ws: print('WebSocket backpressure: %i' % ws.get_buffered_amount())
    })

app = App()
make_app(app)

app.listen(AppListenOptions(port=5555, host="0.0.0.0"), lambda config: print(f"Listening on port http://{config.host}:%d now\n" % (config.port)))
app.run()
```
