### ISSUE TITLE
windows unable to install

### ISSUE THREAD

**Issue by lastmeta** [cirospaciari/socketify.py#37]
**Describe the bug**
missing `libsocketify_windows_amd64.dll`

```
PS C:\repos> pip install git+https://github.com/cirospaciari/socketify.py.git
Collecting git+https://github.com/cirospaciari/socketify.py.git
  Cloning https://github.com/cirospaciari/socketify.py.git to c:\users\j\appdata\local\temp\pip-req-build-kpb0nw3_
  Running command git clone --filter=blob:none --quiet https://github.com/cirospaciari/socketify.py.git 'C:\Users\j\AppData\Local\Temp\pip-req-build-kpb0nw3_'
  Resolved https://github.com/cirospaciari/socketify.py.git to commit 594e5b8474a5d7cb8e7c6aa29fb150017f69ddb9
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cffi>=1.0.0 in c:\users\j\appdata\local\programs\python\python39\lib\site-packages (from socketify==0.0.1) (1.14.5)
Collecting setuptools>=58.1.0
  Downloading setuptools-65.6.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 7.1 MB/s eta 0:00:00Requirement already satisfied: pycparser in c:\users\j\appdata\local\programs\python\python39\lib\site-packages (from cffi>=1.0.0->socketify==0.0.1) (2.20)
Building wheels for collected packages: socketify
  Building wheel for socketify (setup.py) ... done
  Created wheel for socketify: filename=socketify-0.0.1-cp39-cp39-win_amd64.whl size=3230911 sha256=7750e1c48021342a7361da4c87c1d5ac3c9389b22c4085a6fbc216c2245c72a6
  Stored in directory: C:\Users\j\AppData\Local\Temp\pip-ephem-wheel-cache-ozbggtdg\wheels\ea\5e\75\6917b42888d8f701be2bcb306f24a5a275989a293b3194846c
  Attempting uninstall: setuptools
    Found existing installation: setuptools 56.0.0
    Uninstalling setuptools-56.0.0:
      Successfully uninstalled setuptools-56.0.0
Successfully installed setuptools-65.6.0 socketify-0.0.1

PS C:\repos\pubsub> python .\server.py
Traceback (most recent call last):
  File "C:\repos\pubsub\server.py", line 2, in <module>
    from socketify import App, AppOptions, OpCode, CompressOptions
  File "C:\Users\j\AppData\Local\Programs\Python\Python39\lib\site-packages\socketify\__init__.py", line 1, in <module>
    from .socketify import (
  File "C:\Users\j\AppData\Local\Programs\Python\Python39\lib\site-packages\socketify\socketify.py", line 16, in <module>
    from .loop import Loop
  File "C:\Users\j\AppData\Local\Programs\Python\Python39\lib\site-packages\socketify\loop.py", line 5, in <module>
    from .uv import UVLoop
  File "C:\Users\j\AppData\Local\Programs\Python\Python39\lib\site-packages\socketify\uv.py", line 70, in <module>
    lib = ffi.dlopen(library_path)
  File "C:\Users\j\AppData\Local\Programs\Python\Python39\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\j\AppData\Local\Programs\Python\Python39\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\j\AppData\Local\Programs\Python\Python39\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'C:\Users\j\AppData\Local\Programs\Python\Python39\lib\site-packages\socketify\libsocketify_windows_amd64.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\j\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\socketify\\libsocketify_windows_amd64.dll'
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by cirospaciari** [comment]
I weird I will take a look o think is just a setup.py configuration missing to copy the .dll, I will fix this, as workaround git clone the repository and do an "pip install ." This is working

**Comment by seanr3** [comment]
This looks similar to https://github.com/cirospaciari/socketify.py/discussions/10#discussioncomment-4130057. In my case on macOS the file was copied to the location but still had the issue.

**Comment by cirospaciari** [comment]
> This looks similar to [#10 (reply in thread)](https://github.com/cirospaciari/socketify.py/discussions/10#discussioncomment-4130057). In my case on macOS the file was copied to the location but still had the issue.

This is already in process to be fixed, static linking libraries are needed on MacOS soon both will be fixed

**Comment by cirospaciari** [comment]
@lastmeta solved in windows case was just an setup.py config
![image](https://user-images.githubusercontent.com/6379399/202899389-ed80a926-d9bb-48f5-99f0-1bad2c487a54.png)

@seanr3 follow https://github.com/cirospaciari/socketify.py/issues/34 to see when M2 mac will be solved is not the same issue, the error is similar on the highest message but the solution is way different and its not affecting x64 platforms only macOS M2
